# Generated by Django 4.2.7 on 2024-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intruderaction',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
